language: php
php:
  - 7.1.9
  - 7.2.0

services:
  - mysql

before_install:
  - mysql -e 'CREATE DATABASE spat_project;'

before_script:
  - printf "<?php\nnamespace SPATApp;\nclass Config\n{\nstatic $dbHost = '127.0.0.1';\nstatic $dbUsername = 'root';\nstatic $dbPassword = '';\nstatic $dbName = 'spat_project';\n}" >> config.php
  - composer self-update

install:
  - composer install

script:
  - vendor/bin/phpunit