language: php
php:
  - 7.1.9
  - 7.2.0

services:
  - mysql

before_install:
  - mysql -e 'CREATE DATABASE spat_project;'
  - mysql -u root --default-character-set=utf8 spat_project < schema.sql

before_script:
  - cp config.php-example config.php
  - composer self-update

install:
  - composer install

script:
  - vendor/bin/phpunit